import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import 'primereact/resources/themes/lara-light-indigo/theme.css';  // or any other theme
import 'primereact/resources/primereact.min.css';  // Base PrimeReact styles
import 'primeicons/primeicons.css';  // PrimeIcons (if needed)


import StoreProvider from "../../store/provider";

import Loader from "./Components/Loader";
// import { store } from "../../store/store";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
           <StoreProvider>
         <  Loader/>
                   {children}
                </StoreProvider>
        
      
      </body>
    </html>
  );
}
